//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address_Customer()
        {
            this.Customers = new HashSet<Customers>();
            this.GuaranteeCustomers = new HashSet<GuaranteeCustomers>();
        }
    
        public int AddressID { get; set; }
        public string TambonID_Cus { get; set; }
        public string Zipcode { get; set; }
        public string AddressDetails { get; set; }
        public string Amphur_Cus { get; set; }
        public string Province_Cus { get; set; }
    
        public virtual Tambons Tambons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuaranteeCustomers> GuaranteeCustomers { get; set; }
    }
}
