//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers:MyClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Contracts = new HashSet<Contracts>();
            this.Payments = new HashSet<Payments>();
        }
    
        public string ID_Card_m { get; set; }
        public int titleid { get; set; }
        public string Name_m { get; set; }
        public string Lname_m { get; set; }
        public string tel { get; set; }
        public string Address_m { get; set; }
        public string District_m { get; set; }
        public string Amphur_m { get; set; }
        public string Province_m { get; set; }
        public string Zipcode_m { get; set; }
        public string Career_m { get; set; }
        public decimal Salary_m { get; set; }
        public int Status_m { get; set; }
        public byte[] Image_m { get; set; }
        public byte[] ID_img_m { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual StatusCustomer StatusCustomer { get; set; }
        public virtual title title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
