//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License:MyClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public License()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int LicenseID { get; set; }
        public string LicensePlate { get; set; }
        public string LicenseName { get; set; }
        public string KeepAddressID { get; set; }
        public string District_l { get; set; }
        public string Amphur_l { get; set; }
        public string Province_l { get; set; }
        public string Zipcode_l { get; set; }
        public int LicenseType { get; set; }
        public int LicenseStatusID { get; set; }
        public byte[] Licen_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual LicenseStatusDisplay LicenseStatusDisplay { get; set; }
        public virtual LicenseTypes LicenseTypes { get; set; }
    }
}
