
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Finance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User_Finance
{

    public int UserID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Lname { get; set; }

    public Nullable<int> StatusUser { get; set; }



    public virtual StatusUser StatusUser1 { get; set; }

}

}
