//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Pay
    {
        public string PaymentID { get; set; }
        public string ID_Card_m { get; set; }
        public string NameUser { get; set; }
        public string ContractID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Payment_Money { get; set; }
    }
}
