//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Contract
    {
        public string ContractID { get; set; }
        public string Name_m { get; set; }
        public string Lname_m { get; set; }
        public string titlename { get; set; }
        public decimal Balance { get; set; }
        public decimal Per_Month_Amount { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
    }
}
