//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Guarantee
    {
        public string ID_Card_g { get; set; }
        public string Lname_g { get; set; }
        public string Name_g { get; set; }
        public byte[] ID_img_g { get; set; }
        public byte[] Image_g { get; set; }
        public int Status_g { get; set; }
        public decimal Salary_g { get; set; }
        public string Career_g { get; set; }
        public string Zipcode_g { get; set; }
        public string Province_g { get; set; }
        public string Amphur_g { get; set; }
        public string District_g { get; set; }
        public string Address_g { get; set; }
        public int titleid { get; set; }
        public int StatusID { get; set; }
        public string StatusType { get; set; }
        public int Expr1 { get; set; }
        public string titlename { get; set; }
    }
}
