//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_License
    {
        public int LicenseID { get; set; }
        public string LicensePlate { get; set; }
        public string KeepAddressID { get; set; }
        public string LicenseName { get; set; }
        public string District_l { get; set; }
        public string Amphur_l { get; set; }
        public string Province_l { get; set; }
        public string Zipcode_l { get; set; }
        public byte[] Licen_img { get; set; }
        public string LicenseStatusName { get; set; }
        public string InterestName { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
    }
}
