//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customers
    {
        public string ID_Card_m { get; set; }
        public int titleid { get; set; }
        public string Name_m { get; set; }
        public string Lname_m { get; set; }
        public byte[] ID_img_m { get; set; }
        public byte[] Image_m { get; set; }
        public int Status_m { get; set; }
        public decimal Salary_m { get; set; }
        public string Career_m { get; set; }
        public string Zipcode_m { get; set; }
        public string Province_m { get; set; }
        public string Amphur_m { get; set; }
        public string District_m { get; set; }
        public string Address_m { get; set; }
        public string titlename { get; set; }
        public int Expr1 { get; set; }
        public int StatusID { get; set; }
        public string StatusType { get; set; }
    }
}
